### PR TITLE
Separate Show call from Episodes call

### PR DESCRIPTION
**Pull request by liiight**
Added method to remove of all HTML tags that accompany summary property of show

### CODE REVIEW

**Comment by srob650** [comment]
Looks like this fails the unittesting, and it fails slightly differently on python 2 vs 3.

Python 2 (2 errors)
```
======================================================================
ERROR: test_get_show (test.test_tvmaze.ObjectTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/srob/Git/pytvmaze/test/test_tvmaze.py", line 190, in test_get_show
    show5 = get_show(show_name='utopia', show_country='au', show_network='abc')
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 202, in get_show
    show_language, show_country)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 211, in get_show_by_search
    shows = get_show_list(show_name)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 254, in get_show_list
    for show in shows
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 36, in __init__
    self.summary = self.remove_tags(self.data.get('summary'))
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 89, in remove_tags
    return ''.join(et.fromstring(text).itertext())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 102: ordinal not in range(128)

======================================================================
ERROR: test_get_show_list (test.test_tvmaze.ObjectTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/srob/Git/pytvmaze/test/test_tvmaze.py", line 211, in test_get_show_list
    shows = get_show_list('utopia')
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 254, in get_show_list
    for show in shows
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 36, in __init__
    self.summary = self.remove_tags(self.data.get('summary'))
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 89, in remove_tags
    return ''.join(et.fromstring(text).itertext())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 102: ordinal not in range(128)
```

Python 3 (1 error)
```
======================================================================
ERROR: test_get_show (test.test_tvmaze.ObjectTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/srob/Git/pytvmaze/test/test_tvmaze.py", line 201, in test_get_show
    show7 = get_show(show_name='drunk history', show_language='english')
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 202, in get_show
    show_language, show_country)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 211, in get_show_by_search
    shows = get_show_list(show_name)
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 254, in get_show_list
    for show in shows
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 254, in <listcomp>
    for show in shows
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 36, in __init__
    self.summary = self.remove_tags(self.data.get('summary'))
  File "/Users/srob/Git/pytvmaze/pytvmaze/tvmaze.py", line 89, in remove_tags
    return ''.join(et.fromstring(text).itertext())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 1322, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by srob650** [comment]
Looks like:
1. We need to handle the case of an empty summary
2. We need to ensure utf-8 encoding for the ASCII issue

**Comment by liiight** [comment]
Maybe I'll just switch to regex, seems simpler. This was just a copy paste solution I found on stack :smile:

On an unrelated note, can you fix Person class to explicitly declare properties instead of inheriting from dict?
Also i think a Character class would be cool. 
One last thing, there are many methods that still return a non object output. If some of the methods are internal, it is customary to start then with _ to hide it from external calls.

**Comment by srob650** [comment]
Sounds good.

I'll fix the Person class and think about a character class, although characters don't have a specific endpoint.  I need to look into how they show up in the JSON.

If you're referring to the methods that return the JSON directly from TVMaze then yes they don't return objects.  I didn't know of the underscore custom so I can change that I suppose.  I'm not really sure what other objects make sense to create beyond shows/seasons/episodes/people but I'm open to suggestions.

**Comment by liiight** [comment]
do the test work better now?

**Comment by liiight** [comment]
Heads up, I pushed a commit that will separate show API call from episodes in order to save data. This will probably break a lot of tests but I think this is crucial from a performance stand point.

**Comment by liiight** [comment]
I fixed the tests however more test should probably be added to test without episodes embed.

**Comment by srob650** [comment]
Awesome, will definitely check this stuff out in the next few days.  Work and Thanksgiving may push it until Friday, but merging this is definitely around the corner.  Thanks!

**Pull request merged**
