### PR TITLE
Add in support for next and previous episode lookups.

### PR DESCRIPTION
**Pull request by VeNoMouS**

### CODE REVIEW

**Comment by srob650** [comment]
Doesn't seem to work for me.  Looking into it

**Comment by srob650** [comment]
Figured out the issue.  Might make a slight change and also cleaning up mixed indentation, but I like it.  Thanks for the work!

**Comment by VeNoMouS** [comment]
NP, what issue did you have? yea i noticed that screwed up indentation after i pushed, stupid komodo ...

**Comment by srob650** [comment]
Take at look at previous_episode(), you have copy/paste error and one of the lines still has 'nextepisode' in it.  I've fixed it and am modifying slightly to return earlier and adding @property decorator

**Comment by VeNoMouS** [comment]
ah crap!! , lol cheers, yea it was pretty on the fly coding tbh :P

**Comment by srob650** [comment]
It's all good, you did the hard part lol.  Not that any of this was that hard but you know what I mean.

**Comment by VeNoMouS** [comment]
I can reset my head, and push again if you like?

**Comment by VeNoMouS** [comment]
Yea I know, its the weight of effort kind of thing, I hear where you coming from :P thats why i figured id just do it myself.

**Comment by srob650** [comment]
> I can reset my head, and push again if you like?

Nah no need.  I got sidetracked for a bit but finishing this up now.  I didn't end up doing the early return I was talking about, your way is better.  Also added some missing tests.

**Comment by srob650** [comment]
I'm gonna take a look at issue #36 before merging this to master, see if I can get that taken care of tomorrow and then merge.  Thanks for your work!

**Comment by VeNoMouS** [comment]
nicely done, I wasn't aware of the ```@property``` ... learn something new every day :+1: , re #36 , all good, thanks for accepting the PR

**Comment by srob650** [comment]
Yeah I only recently (this year) learned about `@property` and it's niceties :)

**Pull request merged**
