### PR TITLE
Added exception, changed classes struct and added logging instead of printing

### PR DESCRIPTION
**Pull request by liiight**
Added exception, changed classes struct and added logging instead of printing

### CODE REVIEW

**Comment by srob650** [comment]
Hopefully you've read my response on the tvmaze forums, so you know I want to get these exceptions in place!

It seems like this breaks the fuzzymatch concept though, and perhaps that's something that will need to be restructured to accommodate this model, but I may need your help figuring that out.

Doing a search for "utopia gb" raises the ShowNotFound error immediately when really it needs to error softly and continue in the fuzzymatch module, if that makes sense (sorry if this is a poor explanation).  

As far as I can tell, we either need to add a "default parameter" to the show_search function and use it to not error when calling show_search from the fuzzymatch.py "parse_user_text" function, or we need to duplicate the show_search function and put it into fuzzymatch.py with different error handling.  Let me know what you think or if you have a better suggestion!

**Comment by liiight** [comment]
This might not be the perfect place to discuss everything I have to see but it'll have to do. 
Here are some thoughts without any particular order:

1. I apologize that I submitted something that break current behavior. That's not cool and I should have tested it better.
2. I'm not sure that the whole fuzzymatch is something you should even handle. That is TVMaze responsibility. As I see it, an API library such as this one need to simply 'translate' given API capabilities t into the end user. So for a query like 'get_shows' for example, just return a list of shows objects and let the user decide what to do with it (exactly like you did with show_search btw).
3. If you do want a more specific show retreival method,  I'd do something like this:
```python
def get_show(maze_id=None, tvdb_id=None, tvrage_id=None, show_name=None):
    if not any(maze_id, tvdb_id, tvrage_id, show_name):
        raise InsufficientParametersError
    if maze_id:
       do stuff
    elif tvdb_id:
        do other stuff
```
That way you can have a single method that a user can use to search given any parameter he might have.
4. You should keep your output consistent, meaning always return objects. 
5. Using 'print' is ill advised in a library like we already discussed because your code goes into other people's apps, and you don't want to control their output. This goes back to custom exception and logging.

I hope you take these comments in good spirit because you already did a ton of good work that you can build on.

**Comment by liiight** [comment]
Another thing:
I forgot to mention that if you do want the user to have the ability to fine tune the search via parameter like language, year etc you can change the method signature from above to such:
```python
def get_show(maze_id=None, tvdb_id=None, tvrage_id=None, show_name=None, show_year=None, show_network=None, show_language=None):
    if show_name:
        show = get_show_by_search(show_name, show_year, show_network, show_language)

def get_show_by_search(show_name, show_year, show_network, show_language):
    return query_endpoint(show_name=show_name, show_year=show_year, show_network=show_network, show_language=show_language)
```
or something like that.
The point is that you don't need the user to supply a loose string of text you need to parse, you can (and should) require a closed set of information that isn't mandatory that the user can supply IMO.

**Comment by srob650** [comment]
@liiight This is awesome, thank you!  Lots to reply to but I have to run off for the day, just wanted to let you know that overall I agree and will post a more specific reply later, as well as testing and merging this.

**Comment by liiight** [comment]
No problem. Look into unittests library to add tests.

**Comment by srob650** [comment]
Already have been, it's on my ever-growing list of things to learn :)

**Comment by srob650** [comment]
To follow up on this:

I like all of your suggestions and am working on incorporating them right now, along with merging your PR.  The only point I'm still debating is the whole fuzzymatch situation.  I fully agree that this should be handled by the tvmaze site, however myself and many others have asked the owner to implement this and he seems pretty set on not doing it, at least not anytime soon.  In lieu of that happening, are you suggesting that it fall to the user of this API to add their own matching functionality or that I just refine the process I've created?  Thanks!

**Comment by srob650** [comment]
Building on your suggestion, it would look something like this?

```python
def get_show(maze_id=None, tvdb_id=None, tvrage_id=None, show_name=None,
             show_year=None, show_network=None, show_language=None):
    if maze_id:
        return Show(show_main_info(maze_id, embed='episodes'))
    elif tvdb_id:
        return Show(show_main_info(lookup_tvdb(tvdb_id)['id'],
                                   embed='episodes'))
    elif tvrage_id:
        return Show(show_main_info(lookup_tvrage(tvrage_id)['id'],
                                   embed='episodes'))
    if show_name:
        show = get_show_by_search(show_name, show_year, show_network,
                                  show_language)


def get_show_by_search(show_name, show_year, show_network, show_language):
    shows = get_show_list(show_name=show_name)
    # Code here to match against available parameters


# Return list of Show objects from the TVMaze "Show Search" endpoint
def get_show_list(name):
    shows = show_search(name)
    if shows:
        return [
            Show(show_main_info(show['show']['id'], embed='episodes'))
            for show in shows
            ]
    else:
        raise ShowsNotFound(name + ' did not generate show list')
```

**Comment by srob650** [comment]
@liiight 
Made these changes in new "dev" branch (plus merged your PR), mind giving your thoughts when you have time?

**Comment by liiight** [comment]
I'm a little under the weather, but I hope to take a look soon.

**Comment by srob650** [comment]
Sorry to hear that, hope you feel better soon!

**Comment by liiight** [comment]
Looks really good dude, great job!

**Comment by srob650** [comment]
Awesome, thanks for all of your help!  The only thing I think I'll change to reduce verbosity is the params in get_show, remove the show_ prefix so it looks like
```python
def get_show(maze_id=None, tvdb_id=None, tvrage_id=None, name=None,
             year=None, network=None, language=None, country=None):
```

**Comment by liiight** [comment]
Ok. I'd also recommend adding some documentation in comments of methods that deserve explanation

**Comment by srob650** [comment]
Will do

**Comment by srob650** [comment]
Comments/docstrings updated, feels ready to merge to me

**Comment by liiight** [comment]
Looks good to me too

**Pull request merged**
