### PR TITLE
Changes for python3

### PR DESCRIPTION
**Pull request by brookesy2**
Modified some things so that this will work with python3.

* Moved to urllib
* Changed how the url is requested to line up with urllib
* Changed a print statement

### CODE REVIEW

**Comment by srob650** [comment]
Should be no problem, will confirm and merge later tonight or tomorrow.

**Comment by brookesy2** [comment]
No stress. Will revert to using that instead in the future :)

Thanks for all the speedy responses!

**Comment by srob650** [comment]
This is not backwards compatible with Python 2, but I will re-work it so that it is and post a commit soon.  Thanks!

**Comment by brookesy2** [comment]
Very true, thanks for taking it on though!! :)

**Comment by srob650** [comment]
No problem!

**Pull request closed without merging**
