### PR TITLE
Improved pytvmaze api, to make it a better fit for medusa

### PR DESCRIPTION
**Pull request by p0psicles**
Let's leave it here for now. When lab is done with his changes, it can be merged. And maybe PR'd to upstream.

### CODE REVIEW

**Comment by srob650** [comment]
FYI it looks like you cloned from someone else's clone which is like 300 commits behind (from 6 months ago).

**Comment by p0psicles** [comment]
Last commit it's based on is from march 28 (dev)

**Comment by srob650** [comment]
I must have been looking at something else and got confused, sorry.

**Comment by p0psicles** [comment]
Ooh np. It is still wip. We'll do a PR in comming days. Then you can do a Review and determin if the changed are an improvement.

**Pull request closed without merging**
