### PR TITLE
Fix for fuzzymatch and python3

### PR DESCRIPTION
**Pull request by brookesy2**
Slight change to line 115 of fuzzymatch.py for python3 support.

### CODE REVIEW

**Comment by brookesy2** [comment]
@srob650 So pure and sweet now! :)

**Comment by srob650** [comment]
Hmm, did some further testing and actually although there's no more error, this actually doesn't produce the proper result.  For example, if you did a search of "utopia au" you don't get the Australian show.  I'll dig into the dict ordering in python3 thing more and see if I can come up with an answer.  Let me know if you come up with something too :)

**Comment by brookesy2** [comment]
@srob650 Good man! I will take a look tomorrow. I will close out this pull request :)

**Comment by srob650** [comment]
Figured it out, new commit coming soon

**Comment by brookesy2** [comment]
You da man :)

**Pull request closed without merging**
