### PR TITLE
Fix pytvmaze

### PR DESCRIPTION
**Pull request by labrys**
This has a lot of minor pep changes but the meat of the PR is fixing things like missing exceptions and changing the session to be a class method so you don't recreate the session for every request.

### CODE REVIEW

**Comment by labrys** [comment]
This is still in process - cleaning up more as i go...

**Comment by srob650** [comment]
Yeah I realized that, no worries I'll check back in tomorrow.  Thanks for all the work!

**Comment by labrys** [comment]
No problems

**Comment by labrys** [comment]
Shouldn't have PR'd until it was done :)

**Comment by srob650** [comment]
Reverted dev to its 2.0.7 state, will merge when you are ready.

**Comment by labrys** [comment]
OK.   Those work, but it would keep the commit history cleaner this way :)

**Comment by labrys** [comment]
@srob650 Question about Cast and Crew... not for this PR since it would be a breaking change, but is there a reason that Cast is treated as a collection of people and characters, while Crew is a single person and a type instead of a collection?  Essentially Cast and Crew are the same thing so the structure of both should be fairly similar if not identical.

**Comment by srob650** [comment]
@labrys Because that is how the data is presented in the API, see the endpoints:
http://api.tvmaze.com/shows/1/cast
http://api.tvmaze.com/shows/1/crew

**Comment by labrys** [comment]
No they are both represented as a list of item pairs:
A person and a role.... the role for a Cast member is a Character, while the role for a Crew member is simply its Type.
Also instead of being represented as two lists, the collection should be represented as a list of pair-values.

**Comment by srob650** [comment]
I'm definitely open to changing it for the better.  You seem like you have a lot of experience building API's and this is my first (as a self-taught programmer) so as long as we can minimize transition pain for those already using it I'm open to doing whatever is right for a clean, logical API.

**Comment by labrys** [comment]
Right now I'm trying to break out dependencies so I can further modularize the classes.  If you have some time could you test the premium endpoints as I don't have access to a premium api key.  Also if you have any thing you'd like to discuss i'm in IRC on Freenode as `Labrys` or `Labrys_`.

**Comment by labrys** [comment]
@srob650 just a heads up... until I finish the updates you will have to access the tvmaze api from pytvmaze.tvmaze.  I'll update the init when im done so that remains unchanged, but I want to wait till im done restructuring it so that I don't have to keep updating the import statements.

**Comment by srob650** [comment]
@labrys Cool no worries

**Comment by labrys** [comment]
@srob650 just letting you know im still working on this as time permits... next stage is two major changes combined so it will be a while before its complete.

**Comment by srob650** [comment]
@labrys No worries, I figured.  I just wanted to make sure you saw my comment above about the `retry_adapter`

**Comment by srob650** [comment]
Hey there!  Curious if you are still working on this, some wonderful changes that I'd love to see implemented :)

**Comment by labrys** [comment]
@srob650 yup still am... had to back up on some of my changes because they would be major breaking changes and haven't had a chance to get into it again yet.  Hopefully I'll have some time in a weekend or two but busy studying for a cert for work right now.

**Comment by srob650** [comment]
Right on, just checking in!  Good luck on your cert :)

**Pull request closed without merging**
